[build]
builder = "dockerfile"
dockerfilePath = "./backend/Dockerfile"

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"